### ISSUE TITLE
Can not compatible with Vue@2.5.0+

### ISSUE THREAD

**Issue by bsdfzzzy** [istrib/vuex-typescript#5] opened 2017-10-17 10:12 UTC
Hi, I'm migrating my project from Vue@2.4.2 to Vue@2.5.2 and meanwhile I upgrade vuex from 2.7.1 to 3.0.0. But this repo is depending on 2.3.1. So can you upgrade it? I think most people using this repo need this.

**Comment by vanslly** [comment] 2017-10-20 19:55
@bsdgzzy Have you tried #4?

**Comment by thorning** [comment] 2017-10-26 12:07
I got the same problem. The issue is you end up with multiple definitions from the old and the new versions of Vue from different libraries:
```
ERROR in /mount/node_modules/vuex-typescript/node_modules/vuex/types/vue.d.ts
(9,13): error TS2428: All declarations of 'ComponentOptions' must have identical type parameters.

ERROR in /mount/node_modules/vuex-typescript/node_modules/vuex/types/vue.d.ts
(9,40): error TS2304: Cannot find name 'Vue'.
```
Updating the vuex dependency to 3.0.0 solved it for me

**Comment by istrib** [comment] 2017-11-07 21:04
The newly released version 3.0.1 of `vuex-typescript` is compatible with Vuex 3.x. Vuex is now a peer dependency, so Vuex type definitions won't get installed (and duplicated) along `vuex-typescript`. The library will use type definitions installed explicitly with `Vuex`.

For folks which prefer to stay on `Vuex 2.x` there is now a new version of `vuex-typescript` 2.0.1 in which `Vuex` is also a peer dependency, i.e. no local copy of Vuex will be installed automatically with `vuex-typescript`.

**Comment by cr0cK** [comment] 2017-11-12 22:41
@istrib The 3.x version seems not published on npm yet. Do you plan to publish it soon ?

**Comment by istrib** [comment] 2017-11-13 15:43
It has been published, though NPM thinks it's not latest and installs 2.0.1 by default due to timestamp.
This will work:
```
npm install vuex@3.0.1 --save
npm install vuex-typescript@3.0.1 --save
```
I'll re-publish as 3.0.2 so that NPM recognizes 3.x as the latest.

**Comment by istrib** [comment] 2017-11-13 15:49
`vuex-typescript@3.0.2` will now install by default.

**Comment by bsdfzzzy** [comment] 2017-11-14 09:33
I think it's right now. And this issue can be closed.

**Closed** 2017-11-14 15:04 UTC
